from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('buyer/', views.buyer_dashboard, name='buyer_dashboard'),
    path('post-requirement/', views.post_requirement, name='post_requirement'),
    path('my-requirements/', views.my_requirements, name='my_requirements'),
    path('close-requirement/<int:requirement_id>/', views.close_requirement, name='close_requirement'),
    path('seller/', views.seller_dashboard, name='seller_dashboard'),
    path('buyer-requirements/', views.buyer_requirements, name='buyer_requirements'),
    path('submit-offer/<int:requirement_id>/', views.submit_offer, name='submit_offer'),
    path('update-offer/<int:offer_id>/', views.update_offer, name='update_offer'),
    path('view-offers/<int:requirement_id>/', views.view_offers, name='view_offers'),
    path('select-offer/<int:offer_id>/', views.select_offer, name='select_offer'),
    path('my-offers/', views.my_offers, name='my_offers'),
    path('profile/', views.profile, name='profile'),
    path('notifications/', views.notifications, name='notifications'),
    path('logout/', views.logout_view, name='logout'),
    path('selected-orders/', views.selected_orders, name='selected_orders'),
    path('add-review/<int:order_id>/',views.add_review,name='add_review'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('custom-admin/',views.custom_admin_dashboard,name='custom_admin_dashboard'),
    path('custom-admin/buyers/',views.admin_manage_buyers,name='admin_manage_buyers'),
    path('custom-admin/sellers/',views.admin_manage_sellers,name='admin_manage_sellers'),
    path('custom-admin/requirements/',views.admin_manage_requirements,name='admin_manage_requirements'),
    path('custom-admin/requirements/<int:requirement_id>/close/',views.admin_close_requirement,name='admin_close_requirement'),
    path('custom-admin/offers/<int:offer_id>/remove/',views.admin_remove_offer,name='admin_remove_offer'),
    path('custom-admin/offers/',views.admin_manage_offers,name='admin_manage_offers'),
    path('custom-admin/orders/',views.admin_manage_orders,name='admin_manage_orders'),
    path('custom-admin/reviews/',views.admin_manage_reviews,name='admin_manage_reviews'),
    path('custom-admin/reviews/<int:review_id>/delete/',views.admin_delete_review,name='admin_delete_review'),
    path('custom-admin/logout/',views.custom_admin_logout,name='custom_admin_logout'),
    path('seller/<int:seller_id>/',views.seller_public_profile,name='seller_public_profile'),

]